### PR TITLE
Add two more workloads

### PR DESCRIPTION
**Pull request by hariso**
### Quick checks:

- [x] I have followed the [Code Guidelines](https://github.com/ConduitIO/conduit/blob/main/docs/code_guidelines.md).
- [x] There is no other [pull request](https://github.com/ConduitIO/streaming-benchmarks/pulls) for the same update/change.
- [ ] I have written unit tests.
- [x] I have made sure that the PR is of reasonable size and can be easily reviewed.

### CODE REVIEW

**Review by lovromazgon — APPROVED** [review]
Looks good 👍 

One sidenote, which I'm not sure if I mentioned in any of the previous reviews, but I'll rather say it twice than 0 times. The current approach with read time won't exactly produce the number of messages per second. It will always sleep for the specified time before producing the record, regardless of how much time elapsed since the last time the connector produced a record. Using something like [golang.org/x/time/rate](https://pkg.go.dev/golang.org/x/time/rate) would make this more accurate. Another improvement we could do if/when we have time.

**Comment by hariso** [comment]
> Looks good +1
> 
> One sidenote, which I'm not sure if I mentioned in any of the previous reviews, but I'll rather say it twice than 0 times. The current approach with read time won't exactly produce the number of messages per second. It will always sleep for the specified time before producing the record, regardless of how much time elapsed since the last time the connector produced a record. Using something like [golang.org/x/time/rate](https://pkg.go.dev/golang.org/x/time/rate) would make this more accurate. Another improvement we could do if/when we have time.

You're right. I haven't bothered much with it, because the time it takes to actually generate record is minimal, so it's only at higher rates where we might see the lower rate, and at those rates we actually see a decreased performance. But your suggestion is definitely a great one, I'll open an issue in a bit.

**Comment by lovromazgon** [comment]
To be clear, it's not only the time it takes to generate the record but also the time it takes to send the record to Conduit, which might be a relatively long time if Conduit is slow and can't keep up with the source producing records.

**Comment by hariso** [comment]
> To be clear, it's not only the time it takes to generate the record but also the time it takes to send the record to Conduit, which might be a relatively long time if Conduit is slow and can't keep up with the source producing records.

That's a good point. :+1:

**Pull request merged**
